# Generated by Django 3.2 on 2023-03-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230320_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('volunteer_field', models.CharField(choices=[('food', 'Provide Food'), ('transportation', 'Provide Transportation'), ('shelter', 'Provide Shelter')], max_length=15)),
            ],
        ),
    ]
