# Generated by Django 3.2 on 2023-03-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230319_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpneed',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
