# Generated by Django 3.2 on 2023-03-20 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_helpneed_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpneed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpneed',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpneed',
            name='is_helped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpneed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
