# Generated by Django 3.2 on 2023-04-13 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230413_0432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpProvider',
        ),
    ]
