# Generated by Django 3.2 on 2023-04-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_helpneed_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpneed',
            name='help_class',
            field=models.CharField(choices=[('food', 'Food'), ('shelter', 'Shelter'), ('heating', 'Heating'), ('clothes', 'Clothes'), ('medical_supplies', 'Medical Supplies'), ('hygiene', 'Hygiene Kits')], max_length=20, null=True),
        ),
    ]
