# Generated by Django 3.2 on 2023-04-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_helpneed_help_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpneed',
            name='user_type',
            field=models.CharField(choices=[('victim', 'Victim'), ('volunteer', 'Volunteer')], max_length=20, null=True),
        ),
    ]
