# Generated by Django 3.2 on 2023-04-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_helpneed_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpneed',
            name='name',
        ),
        migrations.AddField(
            model_name='helpneed',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='helpneed',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
