# Generated by Django 3.2 on 2023-05-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_clothesrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesrequest',
            name='size',
            field=models.CharField(choices=[('newborns', 'Age 0-1 '), ('babies', 'Age 1-5'), ('kids', 'Age 5-10'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL')], max_length=50),
        ),
    ]
