# Generated by Django 3.2 on 2023-05-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_clothesrequest_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpneed',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
