# Generated by Django 3.2 on 2023-05-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_helpneed_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpneed',
            name='original_quantity',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
