# Generated by Django 3.2 on 2023-05-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_helpneed_helpers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpneed',
            name='helpers',
        ),
    ]
