# Generated by Django 3.2 on 2023-05-20 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_remove_helpneed_helpers'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpneed',
            name='helpers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
