# Generated by Django 3.2 on 2023-05-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_helpneed_helpers'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpneed',
            name='updated_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
