# Generated by Django 3.2 on 2023-05-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_helpneed_updated_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpneed',
            name='updated_quantity',
        ),
    ]
