# Generated by Django 3.2 on 2023-05-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_helpneed_updated_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpneed',
            name='helpers',
        ),
    ]
