# Generated by Django 3.2 on 2023-05-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20230525_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpneed',
            name='helpers',
        ),
        migrations.DeleteModel(
            name='QuantityChange',
        ),
    ]
