# Generated by Django 3.2 on 2023-05-25 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20230525_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpNeedHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('help_need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.helpneed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('help_need', 'user')},
            },
        ),
        migrations.AddField(
            model_name='helpneed',
            name='helpers',
            field=models.ManyToManyField(through='user.HelpNeedHelper', to=settings.AUTH_USER_MODEL),
        ),
    ]
