# Generated by Django 3.2 on 2023-06-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20230601_1002'),
        ('user', '0032_helpneed_volunteer'),
    ]

    operations = [
    ]
