# Generated by Django 3.2 on 2023-06-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_helpneed_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('lat', models.CharField(default='0', max_length=255)),
                ('lon', models.CharField(default='0', max_length=255)),
            ],
        ),
    ]
