# Generated by Django 3.2 on 2023-06-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_hospitals_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='phone',
        ),
    ]
