# Generated by Django 3.2 on 2023-06-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_remove_hospitals_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='city',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
