# Generated by Django 3.2 on 2023-06-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_hospitals_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='address',
        ),
    ]
