# Generated by Django 3.2 on 2023-06-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_merge_0032_auto_20230601_1002_0032_helpneed_volunteer'),
        ('user', '0037_remove_hospitals_address'),
    ]

    operations = [
    ]
